export const staticProducts = [
  {
    id: 1,
    name: "Product 1",
    price: 50,
    category: "Electronics",
    images: [{ url: "path/to/image1.jpg" }],
    isSoldOut: false,
  },
  {
    id: 2,
    name: "Product 2",
    price: 75,
    category: "Clothing",
    images: [{ url: "path/to/image2.jpg" }],
    isSoldOut: false,
  },
  {
    id: 3,
    name: "Product 3",
    price: 150,
    category: "Electronics",
    images: [{ url: "path/to/image3.jpg" }],
    isSoldOut: false,
  },
  {
    id: 4,
    name: "Product 4",
    price: 225,
    category: "Clothing",
    images: [{ url: "path/to/image4.jpg" }],
    isSoldOut: true,
  },
  {
    id: 5,
    name: "Product 5",
    price: 300,
    category: "Books",
    images: [{ url: "path/to/image5.jpg" }],
    isSoldOut: false,
  },
  {
    id: 6,
    name: "Product 6",
    price: 350,
    category: "Electronics",
    images: [{ url: "path/to/image6.jpg" }],
    isSoldOut: false,
  },
  {
    id: 7,
    name: "Product 7",
    price: 400,
    category: "Clothing",
    images: [{ url: "path/to/image7.jpg" }],
    isSoldOut: false,
  },
  {
    id: 8,
    name: "Product 8",
    price: 450,
    category: "Books",
    images: [{ url: "path/to/image8.jpg" }],
    isSoldOut: true,
  },
  {
    id: 9,
    name: "Product 9",
    price: 500,
    category: "Electronics",
    images: [{ url: "path/to/image9.jpg" }],
    isSoldOut: false,
  },
  {
    id: 10,
    name: "Product 10",
    price: 550,
    category: "Clothing",
    images: [{ url: "path/to/image10.jpg" }],
    isSoldOut: false,
  },
  {
    id: 11,
    name: "Product 11",
    price: 600,
    category: "Books",
    images: [{ url: "path/to/image11.jpg" }],
    isSoldOut: true,
  },
  {
    id: 12,
    name: "Product 12",
    price: 650,
    category: "Electronics",
    images: [{ url: "path/to/image12.jpg" }],
    isSoldOut: false,
  },
  {
    id: 13,
    name: "Product 13",
    price: 700,
    category: "Clothing",
    images: [{ url: "path/to/image13.jpg" }],
    isSoldOut: false,
  },
  {
    id: 14,
    name: "Product 14",
    price: 750,
    category: "Books",
    images: [{ url: "path/to/image14.jpg" }],
    isSoldOut: true,
  },
  {
    id: 15,
    name: "Product 15",
    price: 800,
    category: "Electronics",
    images: [{ url: "path/to/image15.jpg" }],
    isSoldOut: false,
  },
  {
    id: 16,
    name: "Product 16",
    price: 850,
    category: "Clothing",
    images: [{ url: "path/to/image16.jpg" }],
    isSoldOut: false,
  },
  {
    id: 17,
    name: "Product 17",
    price: 900,
    category: "Books",
    images: [{ url: "path/to/image17.jpg" }],
    isSoldOut: true,
  },
  {
    id: 18,
    name: "Product 18",
    price: 950,
    category: "Electronics",
    images: [{ url: "path/to/image18.jpg" }],
    isSoldOut: false,
  },
  {
    id: 19,
    name: "Product 19",
    price: 1000,
    category: "Clothing",
    images: [{ url: "path/to/image19.jpg" }],
    isSoldOut: false,
  },
  {
    id: 20,
    name: "Product 20",
    price: 1050,
    category: "Books",
    images: [{ url: "path/to/image20.jpg" }],
    isSoldOut: true,
  },
  {
    id: 21,
    name: "Product 21",
    price: 1100,
    category: "Electronics",
    images: [{ url: "path/to/image21.jpg" }],
    isSoldOut: false,
  },
  {
    id: 22,
    name: "Product 22",
    price: 1150,
    category: "Clothing",
    images: [{ url: "path/to/image22.jpg" }],
    isSoldOut: false,
  },
  {
    id: 23,
    name: "Product 23",
    price: 1200,
    category: "Books",
    images: [{ url: "path/to/image23.jpg" }],
    isSoldOut: true,
  },
  {
    id: 24,
    name: "Product 24",
    price: 1250,
    category: "Electronics",
    images: [{ url: "path/to/image24.jpg" }],
    isSoldOut: false,
  },
  {
    id: 25,
    name: "Product 25",
    price: 1300,
    category: "Clothing",
    images: [{ url: "path/to/image25.jpg" }],
    isSoldOut: false,
  },
  {
    id: 26,
    name: "Product 26",
    price: 1350,
    category: "Books",
    images: [{ url: "path/to/image26.jpg" }],
    isSoldOut: true,
  },
  {
    id: 27,
    name: "Product 27",
    price: 1400,
    category: "Electronics",
    images: [{ url: "path/to/image27.jpg" }],
    isSoldOut: false,
  },
  {
    id: 28,
    name: "Product 28",
    price: 1450,
    category: "Clothing",
    images: [{ url: "path/to/image28.jpg" }],
    isSoldOut: false,
  },
  {
    id: 29,
    name: "Product 29",
    price: 1500,
    category: "Books",
    images: [{ url: "path/to/image29.jpg" }],
    isSoldOut: true,
  },
  {
    id: 30,
    name: "Product 30",
    price: 1550,
    category: "Electronics",
    images: [{ url: "path/to/image30.jpg" }],
    isSoldOut: false,
  },
];
